# Autogenerated wrapper script for PaPILO_Presolve_jll for aarch64-apple-darwin-libgfortran5
export libpapilo_presolve

using CompilerSupportLibraries_jll
using GMP_jll
using boost_jll
using oneTBB_jll
JLLWrappers.@generate_wrapper_header("PaPILO_Presolve")
JLLWrappers.@declare_library_product(libpapilo_presolve, "@rpath/libpapilo-presolve.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, GMP_jll, boost_jll, oneTBB_jll)
    JLLWrappers.@init_library_product(
        libpapilo_presolve,
        "lib/libpapilo-presolve.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )
    JLLWrappers.@generate_init_footer()
end  # __init__()
