# Autogenerated wrapper script for PaPILO_Presolve_jll for powerpc64le-linux-gnu-libgfortran5-cxx11
export libpapilo_presolve

using CompilerSupportLibraries_jll
using GMP_jll
using boost_jll
using oneTBB_jll
JLLWrappers.@generate_wrapper_header("PaPILO_Presolve")
JLLWrappers.@declare_library_product(libpapilo_presolve, "libpapilo-presolve.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, GMP_jll, boost_jll, oneTBB_jll)
    JLLWrappers.@init_library_product(
        libpapilo_presolve,
        "lib/libpapilo-presolve.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )
    JLLWrappers.@generate_init_footer()
end  # __init__()
